USE MASTER
GO

IF DB_ID('QLDuLich') IS NOT NULL
DROP DATABASE QLDuLich
GO

CREATE DATABASE QLDuLich
GO

USE QLDuLich
GO

CREATE TABLE TINH_THANH
(
	QuocGia char(5),
	MaTinhThanh char(5),
	TenTT nvarchar(30),
	DanSo int,
	DienTich float,
	CONSTRAINT PK_TINH_THANH
	PRIMARY KEY(MaTinhThanh)
)

CREATE TABLE DIEM_THAM_QUAN
(
	MaDTQ char(10),
	TenDTQ nvarchar(30),
	TinhThanh char(5),
	QuocGia char(5),
	DacDiem nvarchar(50),
	CONSTRAINT PK_DIEM_THAM_QUAN
	PRIMARY KEY(MaDTQ)
)

CREATE TABLE QUOC_GIA
(
	MaQG char(5),
	TenQG nvarchar(20),
	ThuDo char(5),
	DanSo int,
	DienTich float,
	CONSTRAINT PK_QUOC_GIA
	PRIMARY KEY(MaQG)
)

ALTER TABLE TINH_THANH ADD
	CONSTRAINT FK_TINH_THANH_QUOC_GIA FOREIGN KEY(QuocGia) REFERENCES QUOC_GIA(MaQG)


ALTER TABLE DIEM_THAM_QUAN ADD
	CONSTRAINT FK_DIEM_THAM_QUAN_TINH_THANH FOREIGN KEY(TinhThanh) REFERENCES TINH_THANH(MaTinhThanh),
	CONSTRAINT FK_DIEM_THAM_QUAN_QUOC_GIA FOREIGN KEY(QuocGia) REFERENCES QUOC_GIA(MaQG)

ALTER TABLE QUOC_GIA ADD
	CONSTRAINT FK_QUOC_GIA_TINH_THANH FOREIGN KEY(ThuDo) REFERENCES TINH_THANH(MaTinhThanh)

INSERT INTO TINH_THANH VALUES
	(NULL,'TT001',N'Hà Nội',2500000,927.39),
	(NULL,'TT002',N'Huế',5344000,5009.00),
	(NULL,'TT003',N'Tokyo',12084000,2187.00)

INSERT INTO QUOC_GIA VALUES
	('QG001',N'Việt Nam','TT001',115000000,331688.00),
	('QG002',N'Nhật Bản','TT003',129500000,337834.00)

INSERT INTO DIEM_THAM_QUAN VALUES
	('DTQ001',N'Văn Miếu','TT001','QG001',N'Di tích cổ'),
	('DTQ002',N'Hoàng lăng','TT002','QG001',N'Di tích cổ'),
	('DTQ003',N'Tháp Tokyo','TT003','QG002',N'Công trình hiện đại')

UPDATE TINH_THANH SET QuocGia='QG001' WHERE MaTinhThanh='TT001'
UPDATE TINH_THANH SET QuocGia='QG001' WHERE MaTinhThanh='TT002'
UPDATE TINH_THANH SET QuocGia='QG002' WHERE MaTinhThanh='TT003'

SELECT * FROM dbo.TINH_THANH
SELECT * FROM dbo.QUOC_GIA
SELECT * FROM dbo.DIEM_THAM_QUAN

/* Hãy liệt kê những điểm tham quan (mã và tên) trong nhữngthành phố có 
diện tích lớn hơn 1/100 diện tích của quốc gia của thành phố đó  */
SELECT DTQ.MaDTQ, DTQ.TenDTQ
FROM DIEM_THAM_QUAN DTQ 
JOIN TINH_THANH TT ON DTQ.TinhThanh=TT.MaTinhThanh 
JOIN QUOC_GIA QG ON QG.MaQG=TT.QuocGia
WHERE TT.DienTich > QG.DienTich/100


/* Hãy liệt kê các quốc gia (mã và tên quốc gia) có hơn 30 tỉnh thành */
SELECT QG.MaQG,QG.TenQG
FROM QUOC_GIA QG JOIN TINH_THANH TT ON QG.MaQG=TT.QuocGia
GROUP BY QG.MaQG,QG.TenQG
HAVING COUNT(TT.MaTinhThanh)>=30



