USE QuanLyDeTai
GO
--Q58-- 
/* Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề. */

----EXCEPT - phép trừ
SELECT DISTINCT GV1.*
FROM GIAOVIEN GV1
WHERE NOT EXISTS
(
	SELECT MACD FROM CHUDE
	EXCEPT
		(SELECT CD2.MACD FROM THAMGIADT TG2, DETAI DT2, CHUDE CD2
		WHERE TG2.MADT = DT2.MADT AND DT2.MACD = CD2.MACD AND TG2.MAGV = GV1.MAGV)
)
----NOT EXISTS - phép chia
SELECT DISTINCT GV1.*
FROM GIAOVIEN GV1, THAMGIADT TG1, DETAI DT1, CHUDE CD1
WHERE GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT AND DT1.MACD = CD1.MACD 
	AND NOT EXISTS
	(
		SELECT * FROM CHUDE CD1 WHERE NOT EXISTS (SELECT *FROM THAMGIADT TG2, DETAI DT2
		WHERE TG2.MADT = DT2.MADT AND DT2.MACD = CD1.MACD AND TG2.MAGV = GV1.MAGV)
	)
----NOT IN 
SELECT DISTINCT GV1.*
FROM GIAOVIEN GV1
WHERE NOT EXISTS
(
	SELECT MACD FROM CHUDE WHERE MACD 
	NOT IN (SELECT CD2.MACD FROM THAMGIADT TG2, DETAI DT2, CHUDE CD2
	WHERE TG2.MADT = DT2.MADT AND DT2.MACD = CD2.MACD AND TG2.MAGV = GV1.MAGV)
)
----COUNT - gom nhóm	
SELECT GV1.HOTEN
FROM GIAOVIEN GV1, THAMGIADT TG1, DETAI DT1, CHUDE CD1
WHERE GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT AND DT1.MACD = CD1.MACD
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT CD1.MACD) = (SELECT COUNT(*) FROM CHUDE)

--Q59-- 
/* Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia. */

----EXCEPT - phép trừ
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( --Những GV mà đề tài tg1.MaDT không được tham gia
                (SELECT GV.MAGV FROM GIAOVIEN GV --Tất cả các giáo viên HTTT
				 WHERE GV.MABM = 'HTTT')   
                EXCEPT 
				(SELECT TG2.MAGV FROM THAMGIADT TG2 --những GV mà tg1.MADT đã được tham gia
				 WHERE TG1.MADT = TG2.MADT))
----NOT EXISTS - phép chia
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( --Những GV mà đề tài tg1.MaDT không được tham gia
               SELECT * FROM GIAOVIEN GV
			   WHERE GV.MABM = 'HTTT'
			   AND NOT EXISTS (SELECT *
			                     FROM THAMGIADT TG2
								 WHERE TG2.MADT = TG1.MADT
								 AND GV.MAGV = TG2.MAGV)) 
---- NOT IN
SELECT DT.TENDT 
FROM DETAI DT
WHERE NOT EXISTS (SELECT * FROM GIAOVIEN GV
		          WHERE GV.MABM = 'HTTT' AND GV.MAGV 
				  NOT IN 
				  (SELECT TG.MAGV FROM THAMGIADT TG
				   WHERE TG.MADT = DT.MADT))
----COUNT - gom nhóm					
SELECT DISTINCT TG1.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT AND TG1.MAGV IN (SELECT MAGV FROM GIAOVIEN
                                          WHERE MABM = 'HTTT')
										  GROUP BY TG1.MADT, DT.TENDT
										  HAVING COUNT(DISTINCT TG1.MAGV) = 
										  (SELECT COUNT(MAGV) FROM GIAOVIEN
										  WHERE MABM = 'HTTT')
 
--Q60--
/* Cho biết tên đề tài có tất cả giảng viên bộ môn “Hệ thống thông tin” tham gia */
----EXCEPT - phép trừ
SELECT DISTINCT DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( --Những GV mà đề tài tg1.MaDT không được tham gia
                (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM --Tất cả các giáo viên HTTT
				 WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin')   
                EXCEPT 
				(SELECT TG2.MAGV FROM THAMGIADT TG2 --những GV mà tg1.MADT đã được tham gia
				 WHERE TG1.MADT = TG2.MADT))
----NOT EXCEPT - phép chia
SELECT DISTINCT DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( --Những GV mà đề tài tg1.MaDT không được tham gia
               SELECT * FROM GIAOVIEN GV, BOMON BM
			   WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
			   AND NOT EXISTS (SELECT *
			                   FROM THAMGIADT TG2
							   WHERE TG2.MADT = TG1.MADT AND GV.MAGV = TG2.MAGV)) 
---- NOT IN
SELECT DT.TENDT 
FROM DETAI DT
WHERE NOT EXISTS (SELECT * FROM GIAOVIEN GV, BOMON BM
				  WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
				  AND GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT TG
									  WHERE TG.MADT = DT.MADT))
----COUNT - gom nhóm
SELECT DISTINCT DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT AND TG1.MAGV IN (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM
                                          WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin')
										  GROUP BY TG1.MADT, DT.TENDT
										  HAVING COUNT(DISTINCT TG1.MAGV) = 
										  (SELECT COUNT(GV1.MAGV) FROM GIAOVIEN GV1, BOMON BM1
										  WHERE GV1.MABM = BM1.MABM AND BM1.TENBM = N'Hệ thống thông tin')

--Q61--
/* Cho biết giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD.*/
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT MADT FROM DETAI WHERE MACD = 'QLGD')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV)) 
----NOT EXCEPT - phép chia
SELECT TG1.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT * FROM DETAI DT 
                 WHERE MACD = 'QLGD' 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = DT.MADT AND TG2.MAGV=TG1.MAGV))
---- NOT IN
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS((SELECT * FROM DETAI DT
				  WHERE DT.MACD = 'QLGD' AND DT.MADT 
				  NOT IN (SELECT TG.MADT FROM THAMGIADT TG
					      WHERE TG.MAGV = GV.MAGV)))
----COUNT - gom nhóm
SELECT TG1.MAGV , GV.HOTEN 
FROM THAMGIADT TG1 , GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV AND TG1.MADT IN (SELECT MADT FROM DETAI 
                                          WHERE MACD='QLGD') 
										  GROUP BY TG1.MAGV , GV.HOTEN 
										  HAVING COUNT(DISTINCT TG1.MADT) = 
										  (SELECT COUNT(MADT) FROM DETAI 
										  WHERE MACD = 'QLGD')

--Q62--
/* Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia. */
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT DT.MADT FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
                WHERE DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV AND GV.HOTEN = N'Trần Trà Hương')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV))
----NOT EXCEPT - phép chia
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT DT.* FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
                WHERE DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV AND GV.HOTEN = N'Trần Trà Hương' 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = DT.MADT AND TG2.MAGV=TG1.MAGV))
---- NOT IN
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT * FROM THAMGIADT TG, GIAOVIEN GV1
				  WHERE TG.MAGV = GV1.MAGV AND GV1.HOTEN = N'Trần Trà Hương'
				  AND TG.MADT 
				  NOT IN( SELECT TG1.MADT FROM THAMGIADT TG1
				  WHERE TG1.MAGV = GV.MAGV  AND GV.HOTEN <>N'Trần Trà Hương'))
----COUNT - gom nhóm
SELECT TG1.MAGV, GV.HOTEN 
FROM THAMGIADT TG1 , GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV AND TG1.MADT IN (SELECT DT.MADT FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
                                          WHERE DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV 
										  AND GV.HOTEN = N'Trần Trà Hương') 
										  GROUP BY TG1.MAGV , GV.HOTEN 
										  HAVING COUNT(DISTINCT TG1.MADT) = 
										  (SELECT COUNT(DT.MADT) FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
                                          WHERE DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV 
										  AND GV.HOTEN = N'Trần Trà Hương')

--Q63--
/* Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu Cơ tham gia. */
----EXCEPT - phép trừ
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( 
                (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM
				 WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hóa Hữu Cơ')   
                EXCEPT 
				(SELECT TG2.MAGV FROM THAMGIADT TG2 
				 WHERE TG1.MADT = TG2.MADT))
----NOT EXCEPT - phép chia
SELECT DISTINCT TG1.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( 
               SELECT * FROM GIAOVIEN GV, BOMON BM
			   WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hóa Hữu Cơ'
			   AND NOT EXISTS (SELECT *
			                     FROM THAMGIADT TG2
								 WHERE TG2.MADT = TG1.MADT
								 AND GV.MAGV = TG2.MAGV)) 
---- NOT IN
SELECT DT.TENDT 
FROM DETAI DT
WHERE NOT EXISTS ( SELECT * FROM GIAOVIEN GV, BOMON BM
				   WHERE GV.MABM = BM.MABM AND BM.TENBM = N'HOÁ HỮU CƠ'
				   AND GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT TG
									   WHERE TG.MADT = DT.MADT))
--COUNT - gom nhóm
SELECT DISTINCT TG1.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT AND TG1.MAGV IN (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM
                                          WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hóa Hữu Cơ')
										  GROUP BY TG1.MADT, DT.TENDT
										  HAVING COUNT(DISTINCT TG1.MAGV) = 
										  (SELECT COUNT(GV1.MAGV) FROM GIAOVIEN GV1, BOMON BM1
										  WHERE GV1.MABM = BM1.MABM AND BM1.TENBM = N'Hóa Hữu Cơ')

--Q64--
/* Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006. */
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT MADT FROM CONGVIEC 
                WHERE MADT = '006')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV)) 
----NOT EXCEPT - phép chia
SELECT DISTINCT TG1.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT CV.* FROM CONGVIEC CV 
                 WHERE CV.MADT = '006' 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = CV.MADT AND TG2.MAGV=TG1.MAGV))

---- NOT IN
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
				  SELECT * FROM CONGVIEC CV
				  WHERE CV.MADT = '006' AND CV.SOTT NOT IN (SELECT TG.STT FROM THAMGIADT TG
															WHERE TG.MAGV = GV.MAGV AND TG.MADT = '006'))
----COUNT - gom nhóm
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT = '006'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(TG.STT) = (SELECT COUNT(*)
						FROM CONGVIEC
						WHERE MADT = '006')

--Q65--
/* Cho biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ. */
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT DT.MADT FROM DETAI DT, CHUDE CD 
                WHERE DT.MACD = CD.MACD AND CD.TENCD = 'Ứng dụng công nghệ')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV)) 
----NOT EXCEPT - phép chia
SELECT DISTINCT TG1.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT * FROM DETAI DT, CHUDE CD 
                WHERE DT.MACD = CD.MACD AND CD.TENCD = 'Ứng dụng công nghệ' 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = DT.MADT AND TG2.MAGV = TG1.MAGV))

---- NOT IN
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT * FROM DETAI DT, CHUDE CD
				  WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ' 
				  AND DT.MADT NOT IN (SELECT TG.MADT FROM THAMGIADT TG
									  WHERE TG.MAGV = GV.MAGV))
----COUNT - gom nhóm
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT IN (SELECT DT.MADT FROM DETAI DT, CHUDE CD
										WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ')
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(*) FROM DETAI DT1, CHUDE CD1
								  WHERE DT1.MACD = CD1.MACD AND CD1.TENCD = N'Ứng dụng công nghệ')

--Q66--
/* Cho biết tên giáo viên nào đã tham gia tất cả các đề tài của do Trần Trà Hương làm chủ nhiệm. */
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT DT.MADT FROM DETAI DT, GIAOVIEN GV
                WHERE DT.GVCNDT = GV.MAGV AND GV.HOTEN = N'Trần Trà Hương')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV))
----NOT EXCEPT - phép chia
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT DT.* FROM DETAI DT, GIAOVIEN GV
                 WHERE DT.GVCNDT = GV.MAGV AND GV.HOTEN = N'Trần Trà Hương' 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = DT.MADT AND TG2.MAGV = TG1.MAGV))

---- NOT IN
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
				    SELECT * FROM DETAI DT, GIAOVIEN GV1
					WHERE DT.GVCNDT = GV1.MAGV AND GV1.HOTEN = N'Trần Trà Hương'
					AND DT.MADT NOT IN (SELECT TG.MADT FROM THAMGIADT TG
										WHERE TG.MAGV = GV.MAGV))
----COUNT - gom nhóm
SELECT TG1.MAGV, GV.HOTEN 
FROM THAMGIADT TG1 , GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV AND TG1.MADT IN (SELECT DT.MADT FROM DETAI DT, GIAOVIEN GV
                                          WHERE DT.GVCNDT = GV.MAGV AND GV.HOTEN = N'Trần Trà Hương')
										  GROUP BY TG1.MAGV , GV.HOTEN 
										  HAVING COUNT(DISTINCT TG1.MADT) = 
										  (SELECT COUNT(DT.MADT) FROM DETAI DT, GIAOVIEN GV
                                           WHERE DT.GVCNDT = GV.MAGV AND GV.HOTEN = N'Trần Trà Hương')

--Q67--
/* Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia. */
----EXCEPT - phép trừ
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS ( 
                (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM
				 WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT')   
                EXCEPT 
				(SELECT TG2.MAGV FROM THAMGIADT TG2 
				 WHERE TG1.MADT = TG2.MADT))
----NOT EXCEPT - phép chia
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( 
               SELECT * FROM GIAOVIEN GV, BOMON BM
			   WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT'
			   AND NOT EXISTS (SELECT *
			                     FROM THAMGIADT TG2
								 WHERE TG2.MADT = TG1.MADT
								 AND GV.MAGV = TG2.MAGV)) 
---- NOT IN
SELECT DT.MADT, DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
					SELECT * FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT'
							AND GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT TG
												WHERE TG.MADT = DT.MADT))
----COUNT - gom nhóm
SELECT DISTINCT TG1.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT AND TG1.MAGV IN (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM
				                          WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT')
										  GROUP BY TG1.MADT, DT.TENDT
										  HAVING COUNT(DISTINCT TG1.MAGV) = 
										 (SELECT COUNT(GV.MAGV) FROM GIAOVIEN GV, BOMON BM
				                          WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT')

--Q68--
/* Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế bào gốc. */
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT CV.MADT FROM CONGVIEC CV, DETAI DT
                WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2, CONGVIEC CV2 
			    WHERE TG2.MADT = CV2.MADT AND TG2.STT = CV2.SOTT AND TG2.MAGV = TG1.MAGV)) 
----NOT EXCEPT - phép chia
SELECT DISTINCT TG1.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT CV.* FROM CONGVIEC CV, DETAI DT
                 WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = CV.MADT AND TG2.MAGV = TG1.MAGV))
---- NOT IN
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT * FROM CONGVIEC CV, DETAI DT
				  WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
				  AND CV.SOTT NOT IN (SELECT TG.STT FROM THAMGIADT TG
									  WHERE TG.MADT = CV.MADT AND TG.STT = CV.SOTT AND TG.MAGV = GV.MAGV))
----COUNT - gom nhóm
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT = (SELECT DT.MADT FROM DETAI DT
									   WHERE DT.TENDT = N'Nghiên cứu tế bào gốc')
GROUP BY GV.MAGV, GV.HOTEN, TG.MADT
HAVING COUNT(TG.STT) = (SELECT COUNT(*) FROM CONGVIEC CV, DETAI DT
						WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc')

--Q69--
/* Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu? */
----Test bang 300 trieu
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT DT.MADT FROM DETAI DT
                WHERE DT.KINHPHI > 300)
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV))
----NOT EXCEPT - phép chia
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT DT.* FROM DETAI DT
                 WHERE DT.KINHPHI > 300 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = DT.MADT AND TG2.MAGV = TG1.MAGV))

---- NOT IN
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT * FROM DETAI DT
	              WHERE DT.KINHPHI > 100 AND DT.MADT NOT IN (SELECT TG.MADT FROM THAMGIADT TG
															 WHERE TG.MAGV = GV.MAGV))
----COUNT - gom nhóm
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV 
AND TG1.MADT IN(SELECT DT.MADT FROM DETAI DT WHERE DT.KINHPHI > 300)
                GROUP BY GV.MAGV, GV.HOTEN 
                HAVING COUNT(DISTINCT TG1.MADT) = 
			   (SELECT COUNT (DT.MADT) 
                FROM DETAI DT
                WHERE DT.KINHPHI > 300)

--Q70--
/* Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia. */
----EXCEPT - phép trừ
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( 
                (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM, KHOA K
				 WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học')   
                EXCEPT 
				(SELECT TG2.MAGV FROM THAMGIADT TG2 
				 WHERE TG1.MADT = TG2.MADT))
----NOT EXCEPT - phép chia
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT
AND NOT EXISTS( 
               SELECT * FROM GIAOVIEN GV, BOMON BM, KHOA K
			   WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
			   AND NOT EXISTS (SELECT *
			                     FROM THAMGIADT TG2
								 WHERE TG2.MADT = TG1.MADT
								 AND GV.MAGV = TG2.MAGV)) 
---- NOT IN

----COUNT - gom nhóm
SELECT DISTINCT TG1.MADT, DT.TENDT 
FROM DETAI DT, THAMGIADT TG1
WHERE DT.MADT = TG1.MADT AND TG1.MAGV IN (SELECT GV.MAGV FROM GIAOVIEN GV, BOMON BM, KHOA K
				                          WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA 
										  AND K.TENKHOA = N'Sinh học')
										  GROUP BY TG1.MADT, DT.TENDT
										  HAVING COUNT(DISTINCT TG1.MAGV) = 
										 (SELECT COUNT(GV.MAGV) FROM GIAOVIEN GV, BOMON BM, KHOA K
				                          WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
										  AND K.TENKHOA = N'Sinh học')
--Q71--
/* Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của đề tài “Ứng dụng hóa học xanh”. */
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV
AND NOT EXISTS((SELECT CV.MADT FROM CONGVIEC CV, DETAI DT
                WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2, CONGVIEC CV2 
			    WHERE TG2.MADT = CV2.MADT AND TG2.STT = CV2.SOTT AND TG2.MAGV = TG1.MAGV)) 
----NOT EXCEPT - phép chia
SELECT DISTINCT TG1.MAGV, GV.HOTEN, GV.NGSINH
FROM THAMGIADT TG1, GIAOVIEN GV 
WHERE TG1.MAGV = GV.MAGV 
AND NOT EXISTS ( SELECT CV.* FROM CONGVIEC CV, DETAI DT
                 WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh'
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = CV.MADT AND TG2.MAGV = TG1.MAGV))
---- NOT IN

----COUNT - gom nhóm
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(*) FROM CONGVIEC CV, DETAI DT1
						WHERE CV.MADT = DT1.MADT AND DT1.TENDT = N'Ứng dụng hóa học xanh')

--Q72--
/* Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên
tham gia tất cả các đề tài thuộc chủ đề “Nghiên cứu phát triển”. */
----EXCEPT - phép trừ
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, (SELECT GV1.HOTEN 
                                              FROM GIAOVIEN GV1 
											  WHERE GV.GVQLCM = GV1.MAGV) AS CHUNHIEM_CM  
FROM THAMGIADT TG1, GIAOVIEN GV, BOMON BM
WHERE TG1.MAGV = GV.MAGV AND BM.MABM = GV.MABM
AND NOT EXISTS((SELECT DT.MADT FROM DETAI DT, CHUDE CD 
                WHERE DT.MACD = CD.MACD AND CD.TENCD = 'Nghiên cứu phát triển')
                EXCEPT
			   (SELECT TG2.MADT FROM THAMGIADT TG2 
			    WHERE TG2.MAGV = TG1.MAGV)) 
----NOT EXCEPT - phép chia
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, (SELECT GV1.HOTEN 
                                              FROM GIAOVIEN GV1 
											  WHERE GV.GVQLCM = GV1.MAGV) AS CHUNHIEM_CM 
FROM THAMGIADT TG1, GIAOVIEN GV, BOMON BM
WHERE TG1.MAGV = GV.MAGV AND BM.MABM = GV.MABM 
AND NOT EXISTS ( SELECT * FROM DETAI DT, CHUDE CD 
                 WHERE DT.MACD = CD.MACD AND CD.TENCD = 'Nghiên cứu phát triển' 
				 AND NOT EXISTS (SELECT * FROM THAMGIADT TG2
				                 WHERE TG2.MADT = DT.MADT AND TG2.MAGV = TG1.MAGV))
---- NOT IN

----COUNT - gom nhóm
SELECT DISTINCT GV1.MAGV,GV1.HOTEN,GV1.NGSINH 
FROM GIAOVIEN GV,GIAOVIEN GV1,CHUDE CD, DETAI DT, THAMGIADT TGDT 
WHERE GV1.MAGV = GV.GVQLCM  AND DT.MACD = CD.MACD AND TGDT.MAGV = GV.MAGV AND TGDT.MADT = DT.MADT AND DT.MACD = CD.MACD AND CD.TENCD = N'Nghiên cứu phát triển'
GROUP BY GV1.MAGV,GV1.HOTEN,GV1.NGSINH
HAVING COUNT(DISTINCT DT.MADT) =
(SELECT COUNT(DISTINCT DT1.MADT)
FROM DETAI DT1, CHUDE CD1 
WHERE DT1.MACD = CD1.MACD AND CD1.TENCD = N'Nghiên cứu phát triển')
